changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions
  categories:
    - title: Features
      labels:
        - feature
        - feat
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Tests
      labels:
        - test
    - title: Maintenance
      labels:
        - chore
        - ci
        - docs
        - refactor
    - title: Other changes
      labels:
        - "*"
